apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:/iXYD88Xq9o2gcxYZk2F77VaKiafqykugCV9jJwtclTR++C3M+apwA==,iv:Xr4Vpsy4ZFT6LWmo2lxqEt730hoo21EBZK0N+Bcpg+k=,tag:RFZ8kTkX9LP2dQ0abLggJQ==,type:str]
sops:
  age:
    - recipient: age10sua0cru95f0eazkmc4ccjyw2hfeftnhr5psyd67rpvmpxr9w9fs60awaz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMjUxMUgyRjU1K1d3ODBn
        cSt6QnFlc25mVlU2SS9LWUttTDBlWWNTMHk4Cm5NRDZSbVFpQm1lb1JqaWY2MHRX
        ZVVWYkNraWxSeEZ4TkJJWDJ3M2o4dzQKLS0tIDdHTGVWTXQ2QmszbEEyakt4V3ly
        OGhXVTdVSWtKVTJnQllPTVdLenRTWGcKhFaIsqJuZAY2zIju+B8QfsLw74FTtBj9
        VD/cnUsh9Dd22xoMlsJK+FQvCFAv8f3SfRQA8AGFurVmuBpARYaw9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-01T19:30:54Z"
  mac: ENC[AES256_GCM,data:61sNYC9ijYIqR8r3rnvBOFW5xezURGmmplLAnu5o/KYNr0uTYicgcKKU/M+vTeJ3bwd5UildU1ZUBT/bCbcd+BjU8CZv/Y4zefuDM43HN9mNiZ27y9TlY+/nCwcnGeNNS1GvayKKpHpafF1os2JJAkva34+5ZpNzRBdNAcu12Kk=,iv:hUnO+adI1wolSipgRoJbSyAz/9vOpWPFzr99BRgaWlE=,tag:N546Ip9zIUM/jZ9OywHIqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
