apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:8sUWTC0stw7k0Mq3MR/9R1xIKA==,iv:VLHguPNkiaN0NxCOoQ6CszQdvytiq49TNzhNxIdA/IE=,tag:+OVLqFN91+CT4kCkmjbavw==,type:str]
sops:
  age:
    - recipient: age10sua0cru95f0eazkmc4ccjyw2hfeftnhr5psyd67rpvmpxr9w9fs60awaz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbkh4S1l1Ykd0VkdMRjZP
        NWFiV0QwNDBkVkZITkJHMkpWcnZSK1U0eFZrCklWQXRXTTJyS1FtRXhpaVFHdU8r
        TzUzTmxWU242NkIrYWZFcFNtOTJxU1EKLS0tIG1BS25SQ0lMREhZUUNuZDFlZkw5
        WFJOUkRiVnRiaysrelJGM205SHlpeXMKYW0bPEcLM0u4vEVyb6Am4zUzJh6uzIVZ
        ywJ/jmHbixdc5hqJ55Fms+oUf85mhmrb2/ARMUDksupck/sFahKJ5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-01T19:30:54Z"
  mac: ENC[AES256_GCM,data:RhZ5n1YhQ7BBghZVAowQWyhH170+9VXRztOpN7m77IAULCY3bp3LwPU7dhxej6rYkavt1uo22E0AAXFw1/aZB5iig8HuZWFp5BVCC66BFt0J3Obfc/Ain7CjIvv4+uiVwVrKRjJhL/y1PnWUYe3ld1aSwhZAx3uR4pneOFsrwSM=,iv:Z+ISIf5W3p4oKK7dON4U9WsKcx+tm+V5IOHmDpK5MHU=,tag:M0GmI1UsSQz5Gi+hTg4aEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
