apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:8sUWTC0stw7k0Mq3MR/9R1xIKA==,iv:VLHguPNkiaN0NxCOoQ6CszQdvytiq49TNzhNxIdA/IE=,tag:+OVLqFN91+CT4kCkmjbavw==,type:str]
  PROXMOX_HOST: ENC[AES256_GCM,data:Q55xv+L9qYiTCFwS,iv:UCpovz7/FBMcjLj5nnbyF3kFWBO+5PUqZqCKgChaKxs=,tag:IRerT+0EX/oZHlZzOyUc0w==,type:str]
  PROXMOX_CSI_TOKEN_SECRET: ENC[AES256_GCM,data:1yCNk2++C22/Oph8fxd7gYzdR5z/bPf1CETmlqOcZ4hfUhTe,iv:m/ZMsC/N/I7msAEl4XVcqDDuFCVRRSZhNter8dIVk/0=,tag:cMi1UaMlJooQWAXwXEYK3Q==,type:str]
sops:
  age:
    - recipient: age10sua0cru95f0eazkmc4ccjyw2hfeftnhr5psyd67rpvmpxr9w9fs60awaz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbkh4S1l1Ykd0VkdMRjZP
        NWFiV0QwNDBkVkZITkJHMkpWcnZSK1U0eFZrCklWQXRXTTJyS1FtRXhpaVFHdU8r
        TzUzTmxWU242NkIrYWZFcFNtOTJxU1EKLS0tIG1BS25SQ0lMREhZUUNuZDFlZkw5
        WFJOUkRiVnRiaysrelJGM205SHlpeXMKYW0bPEcLM0u4vEVyb6Am4zUzJh6uzIVZ
        ywJ/jmHbixdc5hqJ55Fms+oUf85mhmrb2/ARMUDksupck/sFahKJ5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-01T20:57:28Z"
  mac: ENC[AES256_GCM,data:d8xkerZpGQWI556j7Co4bIDMnYL9FOPzzSx1e4ItEpC8mHlZoaGxFUot56qxN6xaduNQjzakQrTMHUrPXNQ3FJ+iPDkYD7SxGu2BYN+z9smHPZcDiQs+i5xq63fde5OnFaP8bDi1ncVkcmWS9AL+7+2YhHh66jM0IBDABBcmtos=,iv:crDO2BS3eWxZ0o0t/uVD5yHt+JyGrr0P4vav+Spi8dI=,tag:NOkagAsfu5+TBy/+hrPvuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
