apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:yfsaXkaZOppJ6lyJ9+1dXYe4tcpI8451fkYK3nWkskg=,iv:AR/szZDvQo6W0WelmkqExAzsuFCrdivmm+Vk+U+o0U4=,tag:MHIf+AOxnFgT2SeEmVuxXw==,type:str]
sops:
  age:
    - recipient: age10sua0cru95f0eazkmc4ccjyw2hfeftnhr5psyd67rpvmpxr9w9fs60awaz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QnF0Z3NkbzJRUkhVd2pN
        RlIrcERaWmswWE1melcwRmxRYU1OOWFrOUM4CnB0Q2hCN0NuR2RtZjdFTE12dVJW
        ck8wWFFzbHl2MWhhTTZRMlZFNkNzaGsKLS0tIERHa0U3NEp1c0ZubUh3aHFxSW5o
        TFdDeUtFaG4wbEJGc1dWMW56MDZiMmMKjEvgtbOcNxoYyU4rzs9pqfr2Nq793x+m
        zDTljL7BrRLYfilRRLitAAH7vKnKeEqhCSQMUiFzjDZ7dtmqp5XVbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-01T19:30:54Z"
  mac: ENC[AES256_GCM,data:KbtpdJnqlSG1pIRw3NrBC6yuzKx+nBzdW+phMdgsxkJiBPnDduxVLJB96XGHEdMpr/n7wbretFjA9gqQEHy/AaOTOTpPgRDkpDsW5hn7PMzsWm1QpvXnAl1SH9Rl1HNnBsoW13yVeWq4sMa0xfVCDEoyffnhKv1I9rTDUysLtqM=,iv:3OfeTmbML9i4ylI+mNwWJ92ZZG+IIkrFYhK+wXWMbs0=,tag:pipsmeGLSawfHgamBI8UMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
