---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-lvm-thin
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  storage: local-lvm
  cache: writethrough
  csi.storage.k8s.io/fstype: ext4
  ssd: "true"

