apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Ap38PUrjxYVRVUBz7wHMwe/X8OaTQSewpv5Jg907ke4lZ75e+g0VZlgG8sU8f2BGyZL4pDv2NCnCA5JEKqVtnbR84mCi3lA/PkoDEYcs/VCMPEjjeuBGBuYCjTuneUl/PnKTiL/eePEaoR4AlmQZlSM/41AAbkh0OPUeHqS2LJDHUuHF9cbGGg0Oy6naaoUkSoFXOeMZZs4EcrCc5i4nD/mhe+bpWL6kFBmx1mAaO0tR8Vun,iv:rU+L+kfBhKNEFqqQpLLWUV/NRtCW/KDI26wuiSL2HDY=,tag:eqb7Lc3gjwP9kQyZZJK/Rw==,type:str]
sops:
  age:
    - recipient: age10sua0cru95f0eazkmc4ccjyw2hfeftnhr5psyd67rpvmpxr9w9fs60awaz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWXVkSHFDQTF6dy9UclVk
        TEs4bjFaNjFEaFJxM20wTzVMaWNtWUd5VHlvCjFYendjM2VtZjlQTHpWcW05KzVL
        VDNWelowSkcrU1NnSjBtVVVHTm9FRTAKLS0tIEduL25RcjFYUW1RWUI2NGYvd2c3
        bElZSURjTkpCaFlOdGVOcWxDcU13UXMKjpm4pCIX/d/2Bh5kBYq0s6K9sSFVLKaP
        f+O+tB5LlY12ODooM+CQz0XBsgOO9zhG7DtJeNB/U8v/kS/RhTseYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-01T19:30:54Z"
  mac: ENC[AES256_GCM,data:EXRJ/2Csuz4oFWCX+f8gPk4F0I1EZy6vaROR+hNsIYhpxugSDciJH/ujmZlZrucArcVteM8VuRwSYDuWL/F7kqS66BvWMckf7GYvHBSCqCJABJUkyBHrpE0amgZjGzRfmGIiFD6AjjAMotHT7AfITHpbf7m1XtLlnxOe3MzCcRI=,iv:2LxYA/kI1oWMQT2Ei9m+BtwokD/ctVVISmBhEf6tXys=,tag:W2RqCyQ+DtpVZoVzdzUZPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
