apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:53wWEI84ntKzt09qTqMSTJYSIRpqlkVwlJkvHrahx7F8ZUA5yBIssg==,iv:U4yHsFA6a4/xE9ssNUzBxkL7oCk84nnhisMbhD96ezA=,tag:ARvwwpKHBs9YZofwFM1IXg==,type:str]
sops:
  age:
    - recipient: age10sua0cru95f0eazkmc4ccjyw2hfeftnhr5psyd67rpvmpxr9w9fs60awaz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMExqQVFlcHhSenR4SVJt
        clBuY2FFK1IzUlhkZ0QyN3haRWhRMkZVNEVRCjE5enU0MWdhUlZrMk1mKzNYYkhp
        ekJLMHJRY0NUSkhEY2x3b295UTFTNkUKLS0tIGxuZU5BeXBnbnBNcEVJeUNMaGVj
        elo0eDBkSXhIRmtIc0dRNFBFK0tWMEkKksPRrjzLAiUz+uNr0yqkLPr8Z33to81l
        wsxfBXQCK44aMUk0kfKjW72gKAqBrF6B0CMGer06pEbr3kb3fnO/cg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-01T19:30:54Z"
  mac: ENC[AES256_GCM,data:48ZY6bfCcrJ/2ltmHKpYlbjhDJmQfnUeHxYnpQWxtnHKX1Kf8hQoo+tfz9h2YgyJ+NyOEeHjc+kJtAssu5Gun0pPpn6bDgUF36J0KeBKbx4hmOS5tr+iaGb8IccIwj44RK9PjczVjrb+cgrrhpMjDKwLzuhd2tvx8+zX2cIoY2o=,iv:dKJaZQBA+/iTXMrAdIrkXhTQiUs3PFqOdhqy0NP86mE=,tag:XA/D1PUGCXj4paI4xQF69Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
